In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [37]:
Data_X={"hours_std": [10, 8, 5, 2],
        "hours_play": [3, 20, 1, 6],
        "hours_miss": [0, 2, 5, 8],
        "prac_coding":[5, 7, 2, 1]}
Data_Y={"grades":[87, 75, 63, 41]}

Data_X2={"hours_std": [6, 12],
        "hours_play": [6, 5],
        "hours_miss": [4, 0],
        "prac_coding":[3, 6]}

In [38]:
print(Data_X,Data_Y)

{'hours_std': [10, 8, 5, 2], 'hours_play': [3, 20, 1, 6], 'hours_miss': [0, 2, 5, 8], 'prac_coding': [5, 7, 2, 1]} {'grades': [87, 75, 63, 41]}


In [68]:
x1=Data_X["hours_std"]
x2=Data_X["hours_play"]
x3=Data_X["hours_miss"]
x4=Data_X["prac_coding"]
X=np.transpose([x1,x2,x3,x4])
Y=Data_Y["grades"]
x11=Data_X2["hours_std"]
x22=Data_X2["hours_play"]
x33=Data_X2["hours_miss"]
x44=Data_X2["prac_coding"]
X_test=np.transpose([x11,x22,x33,x44])

In [69]:
print(X,X_test)

[[10  3  0  5]
 [ 8 20  2  7]
 [ 5  1  5  2]
 [ 2  6  8  1]] [[ 6  6  4  3]
 [12  5  0  6]]


In [70]:
from sklearn.linear_model import LinearRegression

In [71]:
model = LinearRegression(fit_intercept=True)

In [72]:
model.fit(X,Y)

LinearRegression()

In [73]:
test_predictions = model.predict(X_test)

In [74]:
print(test_predictions)

[58. 94.]
